### ISSUE TITLE
导出pdf后右侧留白问题

### ISSUE THREAD

**Issue by aaa-hui** [hua1995116/react-resume-site#2]
出现时间:2021年3月31日04:58:06
在使用默认主题,选择导出pdf后,tab栏右侧会有留白现象;
问题原因,界面默认右侧滚动条问题
建议解决方案:将rs-view类名的overflow-y: scroll;属性移除;
![界面](https://user-images.githubusercontent.com/74997909/113055205-e5d97b00-91dc-11eb-9530-fc070123bef9.png)
![导出留白预览](https://user-images.githubusercontent.com/74997909/113055383-1c16fa80-91dd-11eb-8587-3e6cd1fe6314.png)
![所处位置](https://user-images.githubusercontent.com/74997909/113055557-4f598980-91dd-11eb-8643-2fa18e64cfe3.png)
![css](https://user-images.githubusercontent.com/74997909/113055670-6f894880-91dd-11eb-85a3-3020bc8ce169.png)

**Comment by hua1995116** [comment]
收到，感谢❤
