### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by JamieSlome** [hua1995116/react-resume-site#20]
Hey there!

I belong to an open source security research community, and a member (@ning1022) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by hua1995116** [comment]
@JamieSlome  I added the file and contact information, thank you very much.

**Comment by JamieSlome** [comment]
@hua1995116 - looks like we sent you an e-mail with details a little while ago.

You can also view the report directly here:

https://huntr.dev/bounties/3d6ce454-150b-4963-86a0-58c27bbee8d8/

It is private and only accessible to maintainers with repository write permissions.

**Comment by hua1995116** [comment]
Thank you very much, I will fix it.

**Comment by JamieSlome** [comment]
@hua1995116 - great 👍
