### ISSUE TITLE
强烈建议：localStorage转sessionStorage

### ISSUE THREAD

**Issue by bigbigDreamer** [hua1995116/react-resume-site#25]
我觉得应该把 `localStorage` 转为 `sessionStorage`。因为毕竟是~~多站点公用~~**同源多页**公用的文件，**且只有`5M`左右大小**，客户端还是少用或者尽可能的不用比较好。

`sessionStorage` 一样可以持久化数据，只不过生命周期结束点在页面关闭。一样可以解决页面刷新，缓存依旧在的问题。

至于页面关闭，缓存丢失，那是用户的选择，站点不用负责。

**Comment by hua1995116** [comment]
localStorage 是单站点 5M，不会影响其他的页面的。sessionStorage 生命周期太短了，遇到网页突然关闭等突然事件，直接丢失数据。

**Comment by bigbigDreamer** [comment]
> localStorage 是单站点 5M，不会影响其他的页面的。sessionStorage 生命周期太短了，遇到网页突然关闭等突然事件，直接丢失数据。

勘误，应该是同源下的多页面：

`xxxx.com/a` & `xxxx.com/b`。

网页关闭的情况：
1. 电脑关机
2. 用户主动关闭
3. 浏览器奔溃 【数据可能丢失】
4. 电脑磁盘损坏 【数据可能丢失】
5. 电脑奔溃 【数据可能丢失】

如果是仅仅为了解决声明周期短的问题去考虑用户体验，是否可以考虑下：以草稿的形式，以一个 固定频次 自动保存在服务端。这样既可以**跨设备**，也可以**跨浏览器**。

这样体验是不是更好点。

**Comment by hua1995116** [comment]
首先固定时间没办法知道用户最后一次修改是否已经保存。（也就是说你列出的5种情况只有固定频次保存都会产生数据丢失）
目前采取的就是 **固定频次** 和 **本地存储**。本地存储能够弥补我开头说的问题，保障了数据的完整性。

**Comment by bigbigDreamer** [comment]
> 

不用关心用户是否手动点击过保存，或许可以直接自动保存。像飞书文档，像 wps 一样

**Comment by hua1995116** [comment]
目前就是自动保存的呀

**Comment by bigbigDreamer** [comment]
> 目前就是自动保存的呀

我知道是自动保存在 `storage`

我的意思是自动保存在服务端，不是本地缓存了。上面的回复已经列举了数据丢失是会丢失本地缓存的。

一来可以**跨设备**，而来可以**跨浏览器**。

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/39019913/150273375-5b3fa627-9f84-4732-96e7-090066df4822.png">

每次修改是不会触发 `xhr`的。

**Comment by hua1995116** [comment]
不可能立马修改立马保存的，2分钟内没有再次修改就会保存。
