### ISSUE TITLE
二级列表导出后会显示多余的空格

### ISSUE THREAD

**Issue by MuseA-5** [hua1995116/react-resume-site#26]
例如在使用以下格式时，
```
- 第一项
  - 第一项嵌套元素
- 第二项
  - 第二项嵌套元素
```
导出后会如下图所示，显示多余的空格
![Xnip2022-02-05_21-59-27](https://user-images.githubusercontent.com/62163340/152645036-4518bed1-d157-461c-8bba-0274f9578ea2.jpg)

在多次测试后发现，直接选中一个模版并且不修改任何内容导出显示的是正常的。在任意修改后都会出现空格多余的情况（一级列表和二级列表后面都会出现空格）。

**Comment by hua1995116** [comment]
收到，我处理一下

**Comment by hua1995116** [comment]
已修复，你查看一下~

**Comment by MuseA-5** [comment]
感谢修复，现在正常了
