### ISSUE TITLE
居中对齐

### ISSUE THREAD

**Issue by lolkt** [hua1995116/react-resume-site#33]
希望能添加居中左对齐， 左右的间距太大了

**Comment by nan980914** [comment]
> 希望能添加居中左对齐， 左右的间距太大了

你指的是哪里呀？

**Comment by lolkt** [comment]
顶部简介的地方 写姓名 性别 中间空白的地方很大

希望能加一个居中左对齐开始书写，这样右边可以留白

**Comment by lolkt** [comment]
![QQ截图20220708112432](https://user-images.githubusercontent.com/3078737/177910952-351b8f31-baf3-440a-a4f5-e22205617f11.png)

**Comment by hua1995116** [comment]
目前是支持这的形式的~ 可以查看这个模板 https://www.mujicv.com/jianlimoban/9fe9c96930027c06/
