### ISSUE TITLE
空白问题和登录问题

### ISSUE THREAD

**Issue by yuang01** [hua1995116/react-resume-site#36]
1. 简历中间莫名会间隔很大的空白间距
2. 选择了模板，已经登陆了，还是会提示当前为试用，请先登录

**Comment by hua1995116** [comment]
方便加 wx：qiufengblue 详细看看么

**Comment by yuang01** [comment]
已经添加您了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月7日(星期天) 晚上6:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hua1995116/react-resume-site] 空白问题和登录问题 (Issue #36)





 
方便加 wx：qiufengblue 详细看看么
