### ISSUE TITLE
yarn start error

### ISSUE THREAD

**Issue by ambodu** [hua1995116/react-resume-site#45]
When I run yarn start, this error appear: 
error: 
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
   
Desktop\react-resume-site\scripts\start.js:11
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
\Desktop\react-resume-site\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

my node version: v18.19.0

**Comment by lilliabi** [comment]
The Node version is incompatible
