### ISSUE TITLE
Firefox下pdf会丢失列表标点

### ISSUE THREAD

**Issue by mrleidesen** [hua1995116/react-resume-site#7]
第一页都是正常的，第二页开始就会不正常，Chrome下正常
![图片](https://user-images.githubusercontent.com/37147926/117226829-12ba2700-ae48-11eb-9c58-612331ad71cc.jpg)

**Comment by hua1995116** [comment]
在没有导出的时候是否也有这个问题？

**Comment by mrleidesen** [comment]
> 在没有导出的时候是否也有这个问题？

预览和导出都有这个问题

**Comment by mrleidesen** [comment]
@hua1995116 现在看了一下，导出正常了，预览的时候还有这个问题

**Comment by hua1995116** [comment]
因为目前是在前端计算，再给后端去导出，可能确实因为不同浏览器下，渲染html不一样，导致之前导出也有问题，我看一下吧。
