### ISSUE TITLE
关于用户的隐私问题

### ISSUE THREAD

**Issue by yanglbme** [hua1995116/react-resume-site#9]
留意到这个写简历的好工具，样式也非常清新，非常赞。👍

这里我有一个疑问，简历会被通过 POST 请求发送到后台。

![image](https://user-images.githubusercontent.com/21008209/120074343-f3bd5680-c0ce-11eb-96e3-bfd410575e6c.png)

不知道你们有没有考虑直接在前端生成简历文件？目前业内有类似的工具，完全基于前端实现：https://resumd.t9t.io/

**Comment by hua1995116** [comment]
这里是为了能够云端存储，方便在不同机器登录使用。之前调研过，采用纯前端下载，业界的相关一些下载的实现，有很多都是只是生产一张图片在转成pdf，链接跳转复制等功能都没办法用，用户体验很差，然后其他的直接调用打印的方式，对于用户说体验侵入性也太强了，那样的方式更像是一个 demo，而不像是一个产品。最终只能采用后端下载的方式了。
